application: grademakerpro
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- static/node_modules/.*

builtins:
- appstats: on
- admin_redirect: on
- deferred: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: "2.7"

handlers:

- url: /api/.*
  script: main.app
  secure: always

- url: /
  static_files: static/app/index.html
  upload: static/app/index.html
  secure: always

- url: /
  static_dir: static/app/
  secure: always

- url: /favicon.ico
  static_files: /static/app/img/favicon.ico
  upload: static/app/img/favicon.ico
  secure: always

- url: /robots.txt
  static_files: /robots.txt
  upload: static/robots.txt
  secure: always

